"""Generate the seed campaigns by running the real pipeline against the real snapshots.

Usage (from the repo root):
    uv run --project api python scripts/seed.py            # all four
    uv run --project api python scripts/seed.py pun        # just one

Writes fixtures/seed/<key>.json and a readable fixtures/seed/REVIEW.md.
Review both before deploying. Fixtures are never hand-edited: if one is wrong,
fix the snapshot or prompt and regenerate.
"""

from __future__ import annotations

import json
import os
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "api" / "src"))

from adapt.env import load_env  # noqa: E402

load_env()
# Generate into a throwaway DB so seeds never mix with local session data.
os.environ["ADAPT_DB_PATH"] = str(Path(tempfile.mkdtemp()) / "seed.db")

from adapt.config import load_config  # noqa: E402
from adapt.db import connect, init_db  # noqa: E402
from adapt.pipeline import create_campaign, execute_run, run_cost, start_run  # noqa: E402
from adapt.seeds import BRIEF, FIXTURE_DIR, MARKETS, SEEDS, export_fixture  # noqa: E402


def review_md(key: str, run_id: str) -> str:
    conn = connect()
    try:
        camp = conn.execute("SELECT c.* FROM campaigns c JOIN runs r ON r.campaign_id=c.id WHERE r.id=?",
                            (run_id,)).fetchone()
        master = json.loads(camp["master_json"])
        out = [f"## {key}: {camp['title']}", "", f"**Master headline:** {master['headline']}  ",
               f"**Master body:** {master['body']}  ", f"**Master CTA:** {master['cta']}", ""]
        bflags = conn.execute("SELECT * FROM flags WHERE run_id=? AND scope='brief' ORDER BY position",
                              (run_id,)).fetchall()
        out.append("**Brief-level flags:** " + ("none" if not bflags else ""))
        out += [f"- {f['severity']} · {f['cites']} · {f['text']}" for f in bflags]
        for v in conn.execute("SELECT * FROM variants WHERE run_id=? ORDER BY market", (run_id,)):
            out += ["", f"### {v['market'].upper()} ({v['step_status']})"]
            if v["error"]:
                out.append(f"Error: {v['error']}")
            if v["draft_json"]:
                d = json.loads(v["draft_json"])
                out += [f"> {d['headline']}  ", f"> {d['body']}  ", f"> {d['cta']}  ", f"> {d['legal']}", ""]
                for ch in conn.execute("SELECT * FROM changes WHERE variant_id=? ORDER BY position", (v["id"],)):
                    out.append(f"- change `{ch['was']}` → `{ch['now']}` cites **{ch['cites']}**: {ch['why']}")
                for u in d["ungrounded"]:
                    out.append(f"- UNGROUNDED `{u['now']}` cited {u['cites']} ({u.get('problem') or 'bad citation'})")
                for f_, spans in d["unmarked"].items():
                    out += [f"- UNMARKED edit in {f_}: `{s}`" for s in spans]
            if v["scores_json"]:
                sc = json.loads(v["scores_json"])
                out.append("- scores: " + ", ".join(f"{s['name']} {s['score']}" for s in sc))
            for f in conn.execute("SELECT * FROM flags WHERE variant_id=? ORDER BY position", (v["id"],)):
                out.append(f"- flag {f['severity']} · {f['cites']} · {f['text']}")
            why = json.loads(v["confidence_why"])
            out.append(f"- confidence: {'LOW, ' + '; '.join(why) if v['low_confidence'] else 'normal'}")
        cost = run_cost(run_id)
        out += ["", f"_{cost['calls']} calls, {cost['input_tokens']} in / {cost['output_tokens']} out tokens, "
                    f"about ${cost['usd']}_", ""]
        return "\n".join(out)
    finally:
        conn.close()


def main(keys: list[str]) -> int:
    cfg = load_config()
    missing = [m for m in MARKETS if m not in cfg.markets]
    if missing:
        print(f"Missing snapshots: {missing}. Add config/markets/<code>.yaml first.", file=sys.stderr)
        return 1
    init_db()
    sections, failed = [], []
    for key in keys:
        seed = SEEDS[key]
        cid = create_campaign(brand="kin", title=seed["title"], brief=BRIEF, master=seed["master"],
                              markets=MARKETS, is_seed=True, seed_key=key)
        rid = start_run(cid, is_seed=True)
        status = execute_run(cfg, rid)
        print(f"{key}: {status}  {run_cost(rid)}")
        if status != "done":
            failed.append(key)
        export_fixture(key, cid, rid)
        sections.append(review_md(key, rid))
    review = FIXTURE_DIR / "REVIEW.md"
    head = "# Seed fixtures for review\n\nGenerated by scripts/seed.py from the real pipeline. Read every change, " \
           "citation and flag before deploying.\n\n"
    existing = {}
    if review.exists() and len(keys) < len(SEEDS):
        for block in review.read_text().split("\n## ")[1:]:
            existing[block.split(":", 1)[0]] = "## " + block
    for key, sec in zip(keys, sections):
        existing[key] = sec
    review.write_text(head + "\n".join(existing[k] for k in SEEDS if k in existing), encoding="utf-8")
    print(f"Wrote {FIXTURE_DIR}")
    return 1 if failed else 0


if __name__ == "__main__":
    wanted = sys.argv[1:] or list(SEEDS)
    unknown = [k for k in wanted if k not in SEEDS]
    if unknown:
        sys.exit(f"Unknown seed(s): {unknown}. Choose from {list(SEEDS)}.")
    sys.exit(main(wanted))
